# Generated by Django 4.1.1 on 2022-09-20 23:01

from django.db import migrations

def create_data(apps, schema_editor):
    print("Here")

    Recipe = apps.get_model('recipe_manager', 'Recipe')

    Recipe(
        source = 'burger.jpg',
        title = 'Delicious Burger Recipe',
        date = '2022-09-18',
        body = 'This is the body text',
        steps = 'This is step 1; This is step 2'
    ).save()
    Recipe(
        source = 'cheese_cake.jpg',
        title = 'Cheese Cake to Blow Your Socks Off',
        date = '2022-09-18',
        body = 'This is the body text',
        steps = 'This is step 1; This is step 2'
    ).save()
    Recipe(
        source = 'tonkotsu.jpg',
        title = 'Pozole with Tokotsu Style Broth',
        date = '2022-09-21',
        body = 'This is the body text',
        steps = 'This is step 1; This is step 2'
    ).save()
    Recipe(
        source = 'softito.jpg',
        title = 'Grandma\'s Homemade Sofrito',
        date = '2022-09-20',
        body = 'This is the body text',
        steps = 'This is step 1; This is step 2'
    ).save()
    Recipe(
        source = 'sopa_de_arroz.jpg',
        title = 'Sopa de Arroz',
        date = '2022-09-20',
        body = 'This is the body text',
        steps = 'This is step 1; This is step 2'
    ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
