# Generated by Django 4.1.1 on 2022-09-25 16:04

from django.db import migrations

def create_data(apps, schema_editor):
    RecipeCollection = apps.get_model('recipe_manager', 'RecipeCollection')

    RecipeCollection(
        name = "featured",
        desc = "A collection of our featured recipes!"
    ).save()
    RecipeCollection(
        name = "fusion",
        desc = "A collection of our fusion recipes!"
    ).save()
    RecipeCollection(
        name = "hispanic",
        desc = "A collection of our hispanic recipes!"
    ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0002_recipe_manager'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
